name: Run linters

on:
  push:
    branches: [main]
    tags: v*
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - run: rustup update
    - run: rustup component add clippy
    - run : cargo clippy --all-targets -- --deny warnings
